### PR TITLE
Fix react native build on Xcode 13

### PR DESCRIPTION
**Pull request by hokyungh**
*Issue #, if available:*
https://github.com/aws-samples/amazon-chime-react-native-demo/issues/146

*Description of changes:*
This is to make temporary fix. Better longterm fix is upgrade react-native and resolve any issue we have upgrading.

By submitting this pull request, I confirm that you can use, modify, copy, and redistribute this contribution, under the terms of your choice.

### CODE REVIEW

**Review by georgezy-amzn — COMMENTED** [review]
With this fix, can it still build with older Xcode version?

**Comment by hokyungh** [comment]
This I am not too sure. I can't really run Xcode 12.

**Comment by georgezy-amzn** [comment]
> This I am not too sure. I can't really run Xcode 12.

I don't think we need to worry about Xcode 12, I mean like Xcode 13.3.

**Comment by hokyungh** [comment]
Yep. I have 13.3

**Review by georgezy-amzn — APPROVED** [review]

**Pull request merged**
